/* Generated By:JJTree: Do not edit this line. AstConcat.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.sun.el.parser;

import javax.el.ELException;
import com.sun.el.lang.EvaluationContext;

public
class AstConcat extends SimpleNode {
    public AstConcat(int id) {
        super(id);
    }

    public Object getValue(EvaluationContext ctx)
            throws ELException {
        return children[0].getValue(ctx).toString() +
               children[1].getValue(ctx).toString();
    }
}
/* JavaCC - OriginalChecksum=fdbd38f9f01787658aad35ad6f9605dc (do not edit this line) */
