/* Generated By:JJTree: Do not edit this line. AstListData.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.sun.el.parser;

import java.util.ArrayList;
import java.util.HashMap;
import javax.el.ELException;
import com.sun.el.lang.EvaluationContext;

public
class AstListData extends SimpleNode {
    public AstListData(int id) {
        super(id);
    }

    public Object getValue(EvaluationContext ctx) {
        ArrayList<Object> list = new ArrayList<Object>();
        HashMap<Object, Object> map = new HashMap<Object, Object>();

        int paramCount = this.jjtGetNumChildren();
        for (int i = 0; i < paramCount; i++) {
            Node entry = this.children[i];
            Object v1 = entry.jjtGetChild(0).getValue(ctx);
            if (entry.jjtGetNumChildren() > 1) {
                // expr -> expr
                map.put(v1, entry.jjtGetChild(1).getValue(ctx));
            } else {
                list.add(v1);
            }
        }
        // It is error to have mixed list entries
        if (list.size() > 0 && map.size() > 0) {
            throw new ELException("Cannot mix list entry with map entry.");
        }
        if (map.size() > 0) {
            return map;
        }
        return list;
    }
}
/* JavaCC - OriginalChecksum=8a3473629ae1a30d3f471a5d92d8554d (do not edit this line) */
