/* Generated By:JJTree: Do not edit this line. AstListData.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.sun.el.parser;

import java.util.ArrayList;
import com.sun.el.lang.EvaluationContext;

public
class AstListData extends SimpleNode {
    public AstListData(int id) {
        super(id);
    }

    public Object getValue(EvaluationContext ctx) {
        ArrayList<Object> list = new ArrayList<Object>();
        int paramCount = this.jjtGetNumChildren();
        for (int i = 0; i < paramCount; i++) {
            list.add(this.children[i].getValue(ctx));
        }
        return list;
    }
}
/* JavaCC - OriginalChecksum=8a3473629ae1a30d3f471a5d92d8554d (do not edit this line) */
