/* Generated By:JJTree: Do not edit this line. AstListEntry.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.sun.el.parser;

public
class AstListEntry extends SimpleNode {
    public AstListEntry(int id) {
      super(id);
    }
}
/* JavaCC - OriginalChecksum=32835e291bc0c491917c4a78ad0bdcea (do not edit this line) */
