/* Generated By:JJTree: Do not edit this line. AstMethodArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package com.sun.el.parser;

import javax.el.ELException;
import com.sun.el.lang.EvaluationContext;

public
class AstMethodArguments extends SimpleNode {
    public AstMethodArguments(int id) {
      super(id);
    }

    Class<?>[] getParamTypes () {
        return null;
    }

    Object[] getParameters(EvaluationContext ctx) throws ELException {

        if (this.children == null)
            return new Object[] {};

        Object[] obj = new Object[this.children.length];
        for (int i = 0; i < obj.length; i++) {
            obj[i] = this.children[i].getValue(ctx);
        }
        return obj;
    }

    @Override
    public boolean isParametersProvided() {
        return true;
    }

}
/* JavaCC - OriginalChecksum=a0084b7a9e80d141ba52d0f6a2cdf11a (do not edit this line) */
