/* Generated By:JJTree: Do not edit this line. AstMethodSuffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

/**
 * @author Jacob Hookom [jacob@hookom.net]
 * @author Kin-man Chung
 * @version $Change
 */

package com.sun.el.parser;

import javax.el.ELException;
import com.sun.el.lang.EvaluationContext;

public
class AstMethodSuffix extends SimpleNode {
    public AstMethodSuffix(int id) {
        super(id);
    }

    String getMethodName() {
        return this.image;
    }

    Class<?>[] getParamTypes () {
        return null;
    }

    Object[] getParameters(EvaluationContext ctx) throws ELException {

        if (this.children == null)
            return new Object[] {};

        Object[] obj = new Object[this.children.length];
        for (int i = 0; i < obj.length; i++) {
            obj[i] = this.children[i].getValue(ctx);
        }
        return obj;
    }

    @Override
    public boolean isParametersProvided() {
        return true;
    }
}
/* JavaCC - OriginalChecksum=adce9316aed8e4a9e376b1484a9fb926 (do not edit this line) */
