/* Generated By:JavaCC: Do not edit this line. ELParserTreeConstants.java Version 5.0 */
package com.sun.el.parser;

public interface ELParserTreeConstants
{
  public int JJTCOMPOSITEEXPRESSION = 0;
  public int JJTLITERALEXPRESSION = 1;
  public int JJTDEFERREDEXPRESSION = 2;
  public int JJTDYNAMICEXPRESSION = 3;
  public int JJTVOID = 4;
  public int JJTSEMICOLON = 5;
  public int JJTASSIGN = 6;
  public int JJTCHOICE = 7;
  public int JJTOR = 8;
  public int JJTAND = 9;
  public int JJTEQUAL = 10;
  public int JJTNOTEQUAL = 11;
  public int JJTLESSTHAN = 12;
  public int JJTGREATERTHAN = 13;
  public int JJTLESSTHANEQUAL = 14;
  public int JJTGREATERTHANEQUAL = 15;
  public int JJTCONCAT = 16;
  public int JJTPLUS = 17;
  public int JJTMINUS = 18;
  public int JJTMULT = 19;
  public int JJTDIV = 20;
  public int JJTMOD = 21;
  public int JJTNEGATIVE = 22;
  public int JJTNOT = 23;
  public int JJTEMPTY = 24;
  public int JJTVALUE = 25;
  public int JJTDOTSUFFIX = 26;
  public int JJTBRACKETSUFFIX = 27;
  public int JJTMETHODARGUMENTS = 28;
  public int JJTLAMBDAEXPRESSION = 29;
  public int JJTLAMBDAEXPRESSIONORCALL = 30;
  public int JJTMAPDATA = 31;
  public int JJTMAPENTRY = 32;
  public int JJTLISTDATA = 33;
  public int JJTTYPE = 34;
  public int JJTIDENTIFIER = 35;
  public int JJTFUNCTION = 36;
  public int JJTTRUE = 37;
  public int JJTFALSE = 38;
  public int JJTFLOATINGPOINT = 39;
  public int JJTINTEGER = 40;
  public int JJTSTRING = 41;
  public int JJTNULL = 42;


  public String[] jjtNodeName = {
    "CompositeExpression",
    "LiteralExpression",
    "DeferredExpression",
    "DynamicExpression",
    "void",
    "SemiColon",
    "Assign",
    "Choice",
    "Or",
    "And",
    "Equal",
    "NotEqual",
    "LessThan",
    "GreaterThan",
    "LessThanEqual",
    "GreaterThanEqual",
    "Concat",
    "Plus",
    "Minus",
    "Mult",
    "Div",
    "Mod",
    "Negative",
    "Not",
    "Empty",
    "Value",
    "DotSuffix",
    "BracketSuffix",
    "MethodArguments",
    "LambdaExpression",
    "LambdaExpressionOrCall",
    "MapData",
    "MapEntry",
    "ListData",
    "Type",
    "Identifier",
    "Function",
    "True",
    "False",
    "FloatingPoint",
    "Integer",
    "String",
    "Null",
  };
}
/* JavaCC - OriginalChecksum=47d82b014c61459433adb056370f7122 (do not edit this line) */
