/* Generated By:JavaCC: Do not edit this line. ELParserTreeConstants.java Version 5.0 */
package com.sun.el.parser;

public interface ELParserTreeConstants
{
  public int JJTCOMPOSITEEXPRESSION = 0;
  public int JJTLITERALEXPRESSION = 1;
  public int JJTDEFERREDEXPRESSION = 2;
  public int JJTDYNAMICEXPRESSION = 3;
  public int JJTVOID = 4;
  public int JJTASSIGN = 5;
  public int JJTCHOICE = 6;
  public int JJTOR = 7;
  public int JJTAND = 8;
  public int JJTEQUAL = 9;
  public int JJTNOTEQUAL = 10;
  public int JJTLESSTHAN = 11;
  public int JJTGREATERTHAN = 12;
  public int JJTLESSTHANEQUAL = 13;
  public int JJTGREATERTHANEQUAL = 14;
  public int JJTCONCAT = 15;
  public int JJTPLUS = 16;
  public int JJTMINUS = 17;
  public int JJTMULT = 18;
  public int JJTDIV = 19;
  public int JJTMOD = 20;
  public int JJTNEGATIVE = 21;
  public int JJTNOT = 22;
  public int JJTEMPTY = 23;
  public int JJTVALUE = 24;
  public int JJTDOTSUFFIX = 25;
  public int JJTBRACKETSUFFIX = 26;
  public int JJTMETHODARGUMENTS = 27;
  public int JJTLAMBDAEXPRESSION = 28;
  public int JJTLISTDATA = 29;
  public int JJTLISTENTRY = 30;
  public int JJTTYPE = 31;
  public int JJTIDENTIFIER = 32;
  public int JJTFUNCTION = 33;
  public int JJTTRUE = 34;
  public int JJTFALSE = 35;
  public int JJTFLOATINGPOINT = 36;
  public int JJTINTEGER = 37;
  public int JJTSTRING = 38;
  public int JJTNULL = 39;


  public String[] jjtNodeName = {
    "CompositeExpression",
    "LiteralExpression",
    "DeferredExpression",
    "DynamicExpression",
    "void",
    "Assign",
    "Choice",
    "Or",
    "And",
    "Equal",
    "NotEqual",
    "LessThan",
    "GreaterThan",
    "LessThanEqual",
    "GreaterThanEqual",
    "Concat",
    "Plus",
    "Minus",
    "Mult",
    "Div",
    "Mod",
    "Negative",
    "Not",
    "Empty",
    "Value",
    "DotSuffix",
    "BracketSuffix",
    "MethodArguments",
    "LambdaExpression",
    "ListData",
    "ListEntry",
    "Type",
    "Identifier",
    "Function",
    "True",
    "False",
    "FloatingPoint",
    "Integer",
    "String",
    "Null",
  };
}
/* JavaCC - OriginalChecksum=f5cd371bea8dfbc9727319e16fc1dc57 (do not edit this line) */
